### ISSUE TITLE
Component status of Prometheus and Alertmanager remains Pending forever

### ISSUE THREAD

**Issue by kesavanvt** [openshift/ocs-osd-deployer#32]
The instance of Prometheus and Alertmanager doesn't seem to have `status` field and thus making the component status to be of `Pending`  

```
status:
  components:
    alertmanager:
      state: Pending
    prometheus:
      state: Pending
    storageCluster:
      state: Ready
  reconcileStrategy: strict
```
