### ISSUE TITLE
ConfigMap deletion mechanism requires invalid label. 

### ISSUE THREAD

**Issue by renan-campos** [openshift/ocs-osd-deployer#51]
I tried to delete the resources using the configmap mechanism and found that the label main.go configures isn't valid for yaml: the slash makes it invalid. 

```
[rcampos@rh-laptop src]$ cat configmapDelete.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocs-converged
  namespace: openshift-storage
data:
  "api.openshift.com/addon-ocs-converged-delete": "true"

[rcampos@rh-laptop src]$ oc create -f configmapDelete.yaml 
The ConfigMap "ocs-converged" is invalid: data[api.openshift.com/addon-ocs-converged-delete]: Invalid value: "api.openshift.com/addon-ocs-converged-delete": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
```
